version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    # volumes:
    #   - zookeeper-data:/var/lib/zookeeper
  
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    # volumes:
    #   - kafka-data:/var/lib/kafka/data
  
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
  
  userservice:
    image: user-service
    container_name: user-service
    ports:
      - '9810:9810'
    environment:
      POSTGRES_HOST: postgres 
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: user_db
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      USER_SERVICE_PORT: 9810
    depends_on:
      - kafka
      - postgres
      - authservice


  expenseservice:
    image: expense-service
    container_name: expense-service
    ports: 
      - '9820:9820'
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: expense_db
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      EXPENSE_SERVICE_PORT: 9820
    depends_on:
      - kafka
      - postgres

  dsservice:
    image: ds-service
    container_name: ds-service
    ports:
      - '8010:8010'
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      OPENAI_API_KEY: EEcG15Lb6jqcblShxssyi6vkfujhBcf6
    depends_on:
      - kafka
      - postgres
      - expenseservice
      - userservice

  authservice:
    image: auth-service
    container_name: auth-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: auth_db
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      AUTH_SERVICE_PORT: 9898
    ports:
      - '9898:9898'
    depends_on:
      - kafka
      - postgres
  
  kong-service:
    image: kong:latest
    volumes:
      - "./kong/config:/usr/local/kong/declarative"
      - "./kong/custom-plugins:/usr/local/share/lua/5.1/kong/plugins"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_LOG_LEVEL: "debug"
      KONG_PLUGINS: "custom-auth"
      KONG_LUA_PACKAGE_PATH: "/usr/local/share/lua/5.1/?.lua;;"
    ports:
      - "8000:8000/tcp"
      - "127.0.0.1:7990:8001/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"
    depends_on:
      - authservice
volumes:
  postgres-db:
    driver: local
  # zookeeper-data:
  #   driver: local
  # kafka-data:
  #   driver: local
