_format_version: "2.1"
_transform: true

services:
  - name: expense-service
    url: http://expenseservice:9820
    routes:
      - name: expense-route
        paths:
          - /api/v1/expenses
        strip_path: false
        preserve_host: false
    plugins:
      - name: custom-auth
        config:
          auth_service_url: "http://authservice:9898/api/v1/auth/ping"

  - name: user-service
    url: http://userservice:9810
    routes:
      - name: user-route
        paths:
          - /api/v1/users
        strip_path: false
        preserve_host: false
    plugins:
      - name: custom-auth
        config:
          auth_service_url: "http://authservice:9898/api/v1/auth/ping"

  - name: auth-service
    url: http://authservice:9898
    routes:
      - name: auth-route
        paths:
          - /api/v1/auth
        strip_path: false
        preserve_host: false

  - name: ds-service
    url: http://dsservice:8010
    routes:
      - name: ds-route
        paths:
          - /api/v1/ds
        strip_path: false
        preserve_host: false
    plugins:
      - name: custom-auth
        config:
          auth_service_url: "http://authservice:9898/api/v1/auth/ping"