name: Deploy Infrastructure

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Deploy Infrastructure
        run: |
          aws cloudformation deploy \
            --template-file cloudformation-template-init-infra.yml \
            --stack-name infra-stack \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Output Infra Stack Info
        run: |
          aws cloudformation describe-stacks \
            --stack-name infra-stack \
            --query 'Stacks[0].Outputs' \
            > infra-stack-output.json
            cat infra-stack-output.json
      
      - name: Upload infra outputs to S3
        env:
          BUCKET_NAME: 'expense-tracker-infra'
          INFRA_OUTPUTS_FILE: 'infra-stack-output.json'
        run: |
          if ! aws s3api head-bucket --bucket-name $BUCKET_NAME 2>/dev/null; then
            aws s3api create-bucket --bucket $BUCKET_NAME --region ${{ env.AWS_REGION }}
          else 
            echo "Bucket $BUCKET_NAME already exists"
          fi
            echo "Uploading infra outputs to S3: $BUCKET_NAME"
            aws s3 cp $INFRA_OUTPUTS_FILE s3://$BUCKET_NAME/$INFRA_OUTPUTS_FILE
            